name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode google-services.json
        run: |
          echo "$FIREBASE_GOOGLE_SERVICE_JSON" | base64 --decode > android/app/google-services.json
        env:
          FIREBASE_GOOGLE_SERVICE_JSON: ${{ secrets.FIREBASE_GOOGLE_SERVICE_JSON }}

      - name: Create assets folder
        run: mkdir -p android/app/src/main/assets

      - name: Grant Permission to gradlew
        run: chmod +x android/gradlew

      - name: Build Release APK
        run: |
          cd android
          ./gradlew assembleRelease -x lintVitalRelease

      - name: Upload APK to Firebase App Distribution
        run: |
          npm install -g firebase-tools

          firebase appdistribution:distribute \
            android/app/build/outputs/apk/release/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --groups "Flatmates" \
            --release-notes "New GitHub Actions build"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk